source 'https://rubygems.org'

gem 'rails', '4.0.0.rc2'

group :development do
  gem 'mysql2', '0.3.11'
end


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '4.0.0.rc2'
  gem 'coffee-rails', '4.0.0'

  gem 'uglifier', '1.3.0'
end

gem 'jquery-rails', '3.0.4'
